name = "datastar"
version = "2.0.0"

description = "Gleam bindings for https://data-star.dev/"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-datastar" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
